export const ClientName = [
    "Citi Bank",
    "Cognizant Technology",
    "Genpact",
    "HiLabs Inc",
    "Hitachi Globallogic",
    "Infosys BPM Ltd",
    "Infosys BPM (Pontoon)",
    "Infosys Limited",
    "Infosys Limited (Pontoon)",
    "Larsen & Toubro Infotech",
    "NNIT",
    "Persistent Systems",
    "Quinnox Consultancy",
    "Sterlite Technologies",
    "Synechron Inc",
    "Tata Consultancy Services",
    "Ampcus/Cox Communications",
    "Ampcus/Asurion",
    "Spruce Infotech",
    "Blue Acorn iCi",
    "Smart Folks Inc",
    "Soft HQ Inc",
    "Infosys McCamish Systems LLC",
    "Emids Technologies",
    "Bravens Inhouse",
    "Other"
];

export const ContractType = [
    { label: "Bravens W2", value: "Bravens W2" },
    { label: "Bravens C2C", value: "Bravens C2C" },
    { label: "Bravens Fulltime", value: "Bravens Fulltime" },
    { label: "Bravens PassThru W2", value: "Bravens PassThru W2" },
    { label: "Bravens PassThru C2C", value: "Bravens PassThru C2C" },
    { label: "Apokrin W2", value: "Apokrin W2" },
    { label: "Apokrin C2C", value: "Apokrin C2C" },
    { label: "BravensTech W2", value: "BravensTech W2" },
    { label: "BravensTech C2C", value: "BravensTech C2C" },
    { label: "Bravens Temp C2C", value: "Bravens Temp C2C" },
    { label: "Apokrin Referral C2C", value: "Apokrin Referral C2C" }
];

export const WorkAuthorization = [
    { label: "US Citizen", value: "US Citizen", },
    { label: "Canadian Citizen", value: "Canadian Citizen", },
    { label: "H1B", value: "H1B", },
    { label: "Green Card", value: "Green Card", },
    { label: "H4 EAD", value: "H4 EAD", },
    { label: "TN", value: "TN", },
    { label: "H1B", value: "H1B", },
    { label: "EAD", value: "EAD", },
    { label: "OPT EAD", value: "OPT EAD", },
    { label: "CPT", value: "CPT", },
    { label: "L2 EAD", value: "L2 EAD", },
    { label: "CPT EAD", value: "CPT EAD", },
    { label: "Other", value: "Other" }
];

export const LocationName = [
    { label: "Alabama (AL)", value: "Alabama (AL)" },
    { label: "Alaska (AK)", value: "Alaska (AK)" },
    { label: "Arizona (AZ)", value: "Arizona (AZ)" },
    { label: "Arkansas (AR)", value: "Arkansas (AR)" },
    { label: "California (CA)", value: "California (CA)" },
    { label: "Colorado (CO)", value: "Colorado (CO)" },
    { label: "Connecticut (CT)", value: "Connecticut (CT)" },
    { label: "Delaware (DE)", value: "Delaware (DE)" },
    { label: "Florida (FL)", value: "Florida (FL)" },
    { label: "Georgia (GA)", value: "Georgia (GA)" },
    { label: "Hawaii (HI)", value: "Hawaii (HI)" },
    { label: "Idaho (ID)", value: "Idaho (ID)" },
    { label: "Illinois (IL)", value: "Illinois (IL)" },
    { label: "Indiana (IN)", value: "Indiana (IN)" },
    { label: "Iowa (IA)", value: "Iowa (IA)" },
    { label: "Kansas (KS)", value: "Kansas (KS)" },
    { label: "Kentucky (KY)", value: "Kentucky (KY)" },
    { label: "Louisiana (LA)", value: "Louisiana (LA)" },
    { label: "Maine (ME)", value: "Maine (ME)" },
    { label: "Maryland (MD)", value: "Maryland (MD)" },
    { label: "Massachusetts (MA)", value: "Massachusetts (MA)" },
    { label: "Michigan (MI)", value: "Michigan (MI)" },
    { label: "Minnesota (MN)", value: "Minnesota (MN)" },
    { label: "Mississippi (MS)", value: "Mississippi (MS)" },
    { label: "Missouri (MO)", value: "Missouri (MO)" },
    { label: "Montana (MT)", value: "Montana (MT)" },
    { label: "Nebraska (NE)", value: "Nebraska (NE)" },
    { label: "Nevada (NV)", value: "Nevada (NV)" },
    { label: "New Hampshire (NH)", value: "New Hampshire (NH)" },
    { label: "New Jersey (NJ)", value: "New Jersey (NJ)" },
    { label: "New Mexico (NM)", value: "New Mexico (NM)" },
    { label: "New York (NY)", value: "New York (NY)" },
    { label: "North Carolina (NC)", value: "North Carolina (NC)" },
    { label: "North Dakota (ND)", value: "North Dakota (ND)" },
    { label: "Ohio (OH)", value: "Ohio (OH)" },
    { label: "Oklahoma (OK)", value: "Oklahoma (OK)" },
    { label: "Oregon (OR)", value: "Oregon (OR)" },
    { label: "Pennsylvania (PA)", value: "Pennsylvania (PA)" },
    { label: "Rhode Island (RI)", value: "Rhode Island (RI)" },
    { label: "South Carolina (SC)", value: "South Carolina (SC)" },
    { label: "South Dakota (SD)", value: "South Dakota (SD)" },
    { label: "Tennessee (TN)", value: "Tennessee (TN)" },
    { label: "Texas (TX)", value: "Texas (TX)" },
    { label: "Utah (UT)", value: "Utah (UT)" },
    { label: "Vermont (VT)", value: "Vermont (VT)" },
    { label: "Virginia (VA)", value: "Virginia (VA)" },
    { label: "Washington (WA)", value: "Washington (WA)" },
    { label: "West Virginia (WV)", value: "West Virginia (WV)" },
    { label: "Wisconsin (WI)", value: "Wisconsin (WI)" },
    { label: "Wyoming (WY)", value: "Wyoming (WY)}" }
];