export const EMPTY_CLIENT_DATA = {
  id: "",
  clientName: "",
  contractType: "",
  endClientName: "",
  mspName: "",
  email: "",
  contactNumber: "",
  faxNumber: "",
  addressId: "",
  line1: "",
  line2: "",
  city: "",
  state: "",
  zipCode: "",
  country: "",
};
export const EMPTY_CLIENT_VALIDATION_DATA = {
  clientNameValid: "",
  contractTypeValid: "",
  endClientNameValid: "",
  mspNameValid: "",
  emailValid: "",
  contactNumberValid: "",
  faxNumberValid: "",
  addressIdValid: "",
  line1Valid: "",
  line2Valid: "",
  cityValid: "",
  stateValid: "",
  zipCodeValid: "",
  countryValid: "",
};
