export const EMPTY_REFERRAL_DATA = {
  companyName: "",
  federalID: "",
  contactPerson: "",
  email: "",
  contactNumber: "",
  faxNumber: "",
  signAuthority: "",
  signAuthorityDesignation: "",
  stateOfIncorporation: "",
  line1: "",
  line2: "",
  city: "",
  state: "",
  zipCode: "",
  country: "",
};

export const EMPTY_REFERRAL_VALIDATION_DATA = {
  companyNameValid: "",
  federalIDValid: "",
  contactPersonValid: "",
  emailValid: "",
  contactNumberValid: "",
  faxNumberValid: "",
  signAuthorityValid: "",
  signAuthorityDesignationValid: "",
  stateOfIncorporationValid: "",
  line1Valid: "",
  line2Valid: "",
  cityValid: "",
  stateValid: "",
  zipCodeValid: "",
  countryValid: "",
};
