//Chetan Patil - [20-07-23] - action types declaration

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
// export const RESET_USER_DETAILS = "RESET_USER_DETAILS";

// export const SIGN_UP = "SIGN_UP";
export const LOGOUT = "LOGOUT";

export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const STOP_LOADING = "STOP_LOADING";
export const START_LOADING = "START_LOADING";
export const LOAD_SCREEN = "LOAD_SCREEN";
export const ALL_DATA = "ALL_DATA";
export const ALL_DATA_ERROR = "ALL_DATA_ERROR";

export const CANDIDATE_DATA = "CANDIDATE_DATA";
export const CANDIDATE_DATA_ERROR = "CANDIDATE_DATA_ERROR";
export const LOCAL_CANDIDATE_DATA = "LOCAL_CANDIDATE_DATA";
export const LOCAL_CANDIDATE_DATA_ERROR = "LOCAL_CANDIDATE_DATA_ERROR";
export const SINGLE_CANDIDATE = "SINGLE_CANDIDATE";
export const SINGLE_CANDIDATE_ERROR = "SINGLE_CANDIDATE_ERROR";

export const LOCAL_CANDIDATE_VALIDATION_DATA =
  "LOCAL_CANDIDATE_VALIDATION_DATA";
export const CANDIDATE_VALIDATION_DATA = "CANDIDATE_VALIDATION_DATA";
export const CANDIDATE_VALIDATION_DATA_ERROR =
  "CANDIDATE_VALIDATION_DATA_ERROR";

export const LOCAL_CLIENT_VALIDATION_DATA = "LOCAL_CLIENT_VALIDATION_DATA";
export const CLIENT_VALIDATION_DATA = "CLIENT_VALIDATION_DATA";
export const CLIENT_VALIDATION_DATA_ERROR = "CLIENT_VALIDATION_DATA_ERROR";

export const LOCAL_VENDOR_VALIDATION_DATA = "LOCAL_VENDOR_VALIDATION_DATA";
export const VENDOR_VALIDATION_DATA = "VENDOR_VALIDATION_DATA";
export const VENDOR_VALIDATION_DATA_ERROR = "VENDOR_VALIDATION_DATA_ERROR";
export const LOCAL_REFERRAL_VALIDATION_DATA = "LOCAL_REFERRAL_VALIDATION_DATA"
export const LOCAL_JOB_VALIDATION_DATA = "LOCAL_JOB_VALIDATION_DATA";
export const JOB_VALIDATION_DATA = "JOB_VALIDATION_DATA";
export const JOB_VALIDATION_DATA_ERROR = "JOB_VALIDATION_DATA_ERROR";
export const REFERRAL_VALIDATION_DATA = "REFERRAL_VALIDATION_DATA";
export const LOCAL_BACKGROUND_CHECK_VALIDATION_DATA =
  "LOCAL_BACKGROUND_CHECK_VALIDATION_DATA";
export const BACKGROUND_CHECK_VALIDATION_DATA =
  "BACKGROUND_CHECK_VALIDATION_DATA";
export const BACKGROUND_CHECK_VALIDATION_DATA_ERROR =
  "BACKGROUND_CHECK_VALIDATION_DATA_ERROR";

export const LOCAL_DOCUMENTATION_VALIDATION_DATA =
  "LOCAL_DOCUMENTATION_VALIDATION_DATA";
export const DOCUMENTATION_VALIDATION_DATA = "DOCUMENTATION_VALIDATION_DATA";
export const DOCUMENTATION_VALIDATION_DATA_ERROR =
  "DOCUMENTATION_VALIDATION_DATA_ERROR";

export const LOCAL_START_END_VALIDATION_DATA =
  "LOCAL_START_END_VALIDATION_DATA";
export const START_END_VALIDATION_DATA = "START_END_VALIDATION_DATA";
export const START_END_VALIDATION_DATA_ERROR =
  "START_END_VALIDATION_DATA_ERROR";

export const LOCAL_RATE_REVISION_VALIDATION_DATA =
  "LOCAL_RATE_REVISION_VALIDATION_DATA";
export const RATE_REVISION_VALIDATION_DATA = "RATE_REVISION_VALIDATION_DATA";
export const RATE_REVISION_VALIDATION_DATA_ERROR =
  "RATE_REVISION_VALIDATION_DATA_ERROR";

export const CLIENT_DATA = "CLIENT_DATA";
export const CLIENT_DATA_ERROR = "CLIENT_DATA_ERROR";
export const LOCAL_CLIENT_DATA = "LOCAL_CLIENT_DATA";
export const LOCAL_CLIENT_DATA_ERROR = "LOCAL_CLIENT_DATA_ERROR";
export const ALL_CLIENT_DATA = "ALL_CLIENT_DATA";
export const ALL_CLIENT_DATA_ERROR = "ALL_CLIENT_DATA_ERROR";
export const SAVED_CLIENT_DATA = "SAVED_CLIENT_DATA";
export const SAVED_CLIENT_DATA_ERROR = "SAVED_CLIENT_DATA_ERROR";

export const VENDOR_DATA = "VENDOR_DATA";
export const VENDOR_DATA_ERROR = "VENDOR_DATA_ERROR";
export const LOCAL_VENDOR_DATA = "LOCAL_VENDOR_DATA";
export const LOCAL_VENDOR_DATA_ERROR = "LOCAL_VENDOR_DATA_ERROR";
export const ALL_VENDOR_DATA = "ALL_VENDOR_DATA";
export const ALL_VENDOR_DATA_ERROR = "ALL_VENDOR_DATA_ERROR";
export const SAVED_VENDOR_DATA = "SAVED_VENDOR_DATA";
export const SAVED_VENDOR_DATA_ERROR = "SAVED_VENDOR_DATA_ERROR";

export const REFERRAL_DATA = "REFERRAL_DATA";
export const REFERRAL_DATA_ERROR = "REFERRAL_DATA_ERROR";
export const LOCAL_REFERRAL_DATA = "LOCAL_REFERRAL_DATA";
export const LOCAL_REFERRAL_DATA_ERROR = "LOCAL_REFERRAL_DATA_ERROR";
export const ALL_REFERRAL_DATA = "ALL_REFERRAL_DATA";
export const ALL_REFERRAL_DATA_ERROR = "ALL_REFERRAL_DATA_ERROR";

export const JOB_DATA = "JOB_DATA";
export const JOB_DATA_ERROR = "JOB_DATA_ERROR";
export const LOCAL_JOB_DATA = "LOCAL_JOB_DATA";
export const LOCAL_JOB_DATA_ERROR = "LOCAL_JOB_DATA_ERROR";
export const ALL_JOB_DATA = "ALL_JOB_DATA";
export const ALL_JOB_DATA_ERROR = "ALL_JOB_DATA_ERROR";
export const SAVED_JOB_DATA = "SAVED_JOB_DATA";
export const SAVED_JOB_DATA_ERROR = "SAVED_JOB_DATA_ERROR";

export const RATE_REVISION_DATA = "RATE_REVISION_DATA";
export const RATE_REVISION_DATA_ERROR = "RATE_REVISION_DATA_ERROR";
export const LOCAL_RATE_REVISION_DATA = "LOCAL_RATE_REVISION_DATA";
export const LOCAL_RATE_REVISION_DATA_ERROR = "LOCAL_RATE_REVISION_DATA_ERROR";
export const SINGLE_RATE_REVISION = "SINGLE_RATE_REVISION";
export const SINGLE_RATE_REVISION_ERROR = "SINGLE_RATE_REVISION_ERROR";

export const SECONDARY_BUTTON = "SECONDARY_BUTTON";
export const SECONDARY_BUTTON_ERROR = "SECONDARY_BUTTON_ERROR";
export const TERTIARY_BUTTON = "TERTIARY_BUTTON";
export const TERTIARY_BUTTON_ERROR = "TERTIARY_BUTTON_ERROR";
export const BACKGROUND_CHECK = "BACKGROUND_CHECK";
export const BACKGROUND_CHECK_ERROR = "BACKGROUND_CHECK_ERROR";
export const SINGLE_BACKGROUND_CHECK = "SINGLE_BACKGROUND_CHECK";
export const SINGLE_BACKGROUND_CHECK_ERROR = "SINGLE_BACKGROUND_CHECK_ERROR";
export const LOCAL_BACKGROUND_CHECK = "LOCAL_BACKGROUND_CHECK";
export const LOCAL_BACKGROUND_CHECK_ERROR = "LOCAL_BACKGROUND_CHECK-ERROR";

export const DOCUMENTATION_DATA = "DOCUMENTATION_DATA";
export const DOCUMENTATION_DATA_ERROR = "DOCUMENTATION_DATA_ERROR";
export const SINGLE_DOCUMENTATION = "SINGLE_DOCUMENTATION";
export const SINGLE_DOCUMENTATION_ERROR = "SINGLE_DOCUMENTATION_ERROR";
export const LOCAL_DOCUMENTATION_DATA = "LOCAL_DOCUMENTATION_DATA";
export const LOCAL_DOCUMENTATION_DATA_ERROR = "LOCAL_DOCUMENTATION_DATA_ERROR";

export const START_END_OPERATIONS_DATA = "START_END_OPERATIONS_DATA";
export const START_END_OPERATIONS_DATA_ERROR =
  "START_END_OPERATIONS_DATA_ERROR";
export const SINGLE_START_END_OPERATIONS = "SINGLE_START_END_OPERATIONS";
export const SINGLE_START_END_OPERATIONS_ERROR =
  "SINGLE_START_END_OPERATIONS_ERROR";
export const LOCAL_START_END_OPERATIONS_DATA =
  "LOCAL_START_END_OPERATIONS_DATA";
export const LOCAL_START_END_OPERATIONS_DATA_ERROR =
  "LOCAL_START_END_OPERATIONS_DATA_ERROR";

export const ALL_WORKAUTHORIZATION_DATA = "ALL_WORKAUTHORIZATION_DATA";
export const ALL_WORKAUTHORIZATION_DATA_ERROR =
  "ALL_WORKAUTHORIZATION_DATA_ERROR";
export const WORKAUTHORIZATION_DATA = "WORKAUTHORIZATION_DATA";
export const WORKAUTHORIZATION_DATA_ERROR = "WORKAUTHORIZATION_DATA_ERROR";
export const LOCAL_WORKAUTHORIZATION_DATA = "LOCAL_WORKAUTHORIZATION_DATA";
export const SAVED_WORKAUTHORIZATION_DATA = "SAVED_WORKAUTHORIZATION_DATA";
export const SAVED_WORKAUTHORIZATION_DATA_ERROR =
  "SAVED_WORKAUTHORIZATION_DATA_ERROR";

export const ALL_CONTRACTTYPE_DATA = "ALL_CONTRACTTYPE_DATA";
export const ALL_CONTRACTTYPE_DATA_ERROR = "ALL_CONTRACTTYPE_DATA_ERROR";
export const CONTRACTTYPE_DATA = "CONTRACTTYPE_DATA";
export const CONTRACTTYPE_DATA_ERROR = "CONTRACTTYPE_DATA_ERROR";
export const LOCAL_CONTRACTTYPE_DATA = "LOCAL_CONTRACTTYPE_DATA";
export const SAVED_CONTRACTTYPE_DATA = "SAVED_CONTRACTTYPE_DATA";
export const SAVED_CONTRACTTYPE_DATA_ERROR = "SAVED_CONTRACTTYPE_DATA_ERROR";

export const ALL_CANDIDATES_DATA = "ALL_CANDIDATES_DATA";
export const ALL_CANDIDATES_DATA_ERROR = "ALL_CANDIDATES_DATA_ERROR";
export const IMPORTANT_CANDIDATE_DATA = "IMPORTANT_CANDIDATE_DATA";
export const IMPORTANT_CANDIDATE_DATA_ERROR = "IMPORTANT_CANDIDATE_DATA_ERROR";

export const EDIT_CANDIDATE_DATA = "EDIT_CANDIDATE_DATA";
export const EDIT_CANDIDATE_DATA_ERROR = "EDIT_CANDIDATE_DATA_ERROR";

export const DELETE_CANDIDATE_DATA = "DELETE_CANDIDATE_DATA";
export const DELETE_CANDIDATE_DATA_ERROR = "DELETE_CANDIDATE_DATA_ERROR";

export const EDIT_CANDIDATE_CLIENT_DATA = "EDIT_CANDIDATE_CLIENT_DATA";
export const EDIT_CANDIDATE_CLIENT_DATA_ERROR =
  "EDIT_CANDIDATE_CLIENT_DATA_ERROR";

export const EDIT_CANDIDATE_JOB_DATA = "EDIT_CANDIDATE_JOB_DATA";
export const EDIT_CANDIDATE_JOB_DATA_ERROR = "EDIT_CANDIDATE_JOB_DATA_ERROR";

export const EDIT_CANDIDATE_VENDOR_DATA = "EDIT_CANDIDATE_VENDOR_DATA";
export const EDIT_CANDIDATE_VENDOR_DATA_ERROR =
  "EDIT_CANDIDATE_VENDOR_DATA_ERROR";

// export const EDIT_CANDIDATE_WORK_AUTHORIZATION_DATA = "EDIT_CANDIDATE_VENDOR_DATA";
// export const EDIT_CANDIDATE_VENDOR_DATA_ERROR =
//   "EDIT_CANDIDATE_VENDOR_DATA_ERROR";

export const GET_CANDIDATE_VENDOR_DATA = "GET_CANDIDATE_VENDOR_DATA";
export const GET_CANDIDATE_VENDOR_DATA_ERROR =
  "GET_CANDIDATE_VENDOR_DATA_ERROR";

export const EDIT_RATEREVISION_DATA = "EDIT_RATEREVISION_DATA";
export const EDIT_RATEREVISION_DATA_ERROR = "EDIT_RATEREVISION_DATA_ERROR";

export const EDIT_START_END_OPERATIONS_DATA = "EDIT_RATEREVISION_DATA";
export const EDIT_START_END_OPERATIONS_DATA_ERROR =
  "EDIT_RATEREVISION_DATA_ERROR";

export const UPDATE_ONLY_CLIENT_DATA = "UPDATE_ONLY_CLIENT_DATA";
export const UPDATE_ONLY_CLIENT_DATA_ERROR = "UPDATE_ONLY_CLIENT_DATA_ERROR";

export const EDIT_CONTACT_DATA = "EDIT_CONTACT_DATA";
export const EDIT_CONTACT_DATA_ERROR = "EDIT_CONTACT_DATA_ERROR";
